import { EventType, EventCategory } from "../../../generated/prisma/enums";
import { prisma } from "../../../src/config/prisma-client.config";

export async function seedEvent() {
  console.log("🌱 Seeding Events...");

  const user = await prisma.user.findMany();

  if (user.length === 0) {
    throw new Error("user type can't be found in DB!");
  }

  const events = [
    {
      eventName: "Music For Life",
      startDate: new Date("2026-06-01T19:00:00"),
      endDate: new Date("2026-06-01T23:00:00"),
      imageUrl: "https://picsum.photos/seed/music/800/400",
      location: "Jakarta",
      description: "Live concert music event featuring local indie bands.",
      seatTotal: 500,
      eventType: EventType.PAID,
      eventCategory: EventCategory.CONCERT,
      userId: user[0].id,
    },
    {
      eventName: "Rock Nation",
      startDate: new Date("2026-06-05T18:00:00"),
      endDate: new Date("2026-06-05T23:30:00"),
      imageUrl: "https://picsum.photos/seed/rock/800/400",
      location: "Bandung",
      description:
        "Experience the heat of rock music with top national performers.",
      seatTotal: 600,
      eventType: EventType.PAID,
      eventCategory: EventCategory.CONCERT,
      userId: user[1].id,
    },
    {
      eventName: "Startup Seminar",
      startDate: new Date("2026-06-10T09:00:00"),
      endDate: new Date("2026-06-10T15:00:00"),
      imageUrl: "https://picsum.photos/seed/startup/800/400",
      location: "Jakarta",
      description: "Learn how to build a scalable startup from the experts.",
      seatTotal: 300,
      eventType: EventType.FREE,
      eventCategory: EventCategory.SEMINAR,
      userId: user[2].id,
    },
    {
      eventName: "Digital Marketing Talk",
      startDate: new Date("2026-06-15T13:00:00"),
      endDate: new Date("2026-06-15T17:00:00"),
      imageUrl: "https://picsum.photos/seed/marketing/800/400",
      location: "Surabaya",
      description: "Marketing seminar focusing on AI and SEO trends in 2026.",
      seatTotal: 250,
      eventType: EventType.FREE,
      eventCategory: EventCategory.SEMINAR,
      userId: user[3].id,
    },
    {
      eventName: "City Fun Run",
      startDate: new Date("2026-06-20T05:30:00"),
      endDate: new Date("2026-06-20T10:00:00"),
      imageUrl: "https://picsum.photos/seed/run/800/400",
      location: "Bogor",
      description:
        "A healthy morning fun run around the beautiful Bogor Botanical Garden.",
      seatTotal: 800,
      eventType: EventType.FREE,
      eventCategory: EventCategory.SPORTS,
      userId: user[4].id,
    },
    {
      eventName: "National Badminton Cup",
      startDate: new Date("2026-06-25T08:00:00"),
      endDate: new Date("2026-06-27T21:00:00"),
      imageUrl: "https://picsum.photos/seed/badminton/800/400",
      location: "Jakarta",
      description: "The biggest annual amateur badminton tournament.",
      seatTotal: 1000,
      eventType: EventType.PAID,
      eventCategory: EventCategory.SPORTS,
      userId: user[5].id,
    },
    {
      eventName: "Frontend Workshop",
      startDate: new Date("2026-07-01T09:00:00"),
      endDate: new Date("2026-07-01T17:00:00"),
      imageUrl: "https://picsum.photos/seed/frontend/800/400",
      location: "Yogyakarta",
      description:
        "Intensive workshop on React and Next.js performance tuning.",
      seatTotal: 100,
      eventType: EventType.PAID,
      eventCategory: EventCategory.WORKSHOP,
      userId: user[6].id,
    },
    {
      eventName: "Backend Masterclass",
      startDate: new Date("2026-07-03T09:00:00"),
      endDate: new Date("2026-07-04T17:00:00"),
      imageUrl: "https://picsum.photos/seed/backend/800/400",
      location: "Malang",
      description: "Mastering Node.js microservices and database optimization.",
      seatTotal: 120,
      eventType: EventType.PAID,
      eventCategory: EventCategory.WORKSHOP,
      userId: user[7].id,
    },
    {
      eventName: "Modern Art Expo",
      startDate: new Date("2026-07-10T10:00:00"),
      endDate: new Date("2026-07-15T21:00:00"),
      imageUrl: "https://picsum.photos/seed/art/800/400",
      location: "Bali",
      description: "Showcasing contemporary masterpieces from Southeast Asia.",
      seatTotal: 400,
      eventType: EventType.PAID,
      eventCategory: EventCategory.EXHIBITION,
      userId: user[8].id,
    },
    {
      eventName: "Photography Exhibition",
      startDate: new Date("2026-07-12T10:00:00"),
      endDate: new Date("2026-07-14T20:00:00"),
      imageUrl: "https://picsum.photos/seed/photo/800/400",
      location: "Jakarta",
      description: "A collective photography showcase of urban life.",
      seatTotal: 350,
      eventType: EventType.FREE,
      eventCategory: EventCategory.EXHIBITION,
      userId: user[9].id,
    },
    {
      eventName: "Drama Theatre Night",
      startDate: new Date("2026-07-18T19:30:00"),
      endDate: new Date("2026-07-18T22:00:00"),
      imageUrl: "https://picsum.photos/seed/drama/800/400",
      location: "Jakarta",
      description:
        "A classic drama performance by the national theater troupe.",
      seatTotal: 200,
      eventType: EventType.PAID,
      eventCategory: EventCategory.THEATER,
      userId: user[10].id,
    },
    {
      eventName: "Comedy Theatre Show",
      startDate: new Date("2026-07-20T20:00:00"),
      endDate: new Date("2026-07-20T22:30:00"),
      imageUrl: "https://picsum.photos/seed/comedy/800/400",
      location: "Bandung",
      description: "Laugh until you drop with our comedy stage performance.",
      seatTotal: 220,
      eventType: EventType.PAID,
      eventCategory: EventCategory.THEATER,
      userId: user[11].id,
    },
    {
      eventName: "Summer Festival",
      startDate: new Date("2026-08-01T15:00:00"),
      endDate: new Date("2026-08-03T23:00:00"),
      imageUrl: "https://picsum.photos/seed/summer/800/400",
      location: "Bali",
      description: "Celebrate summer with beach activities and cultural shows.",
      seatTotal: 900,
      eventType: EventType.FREE,
      eventCategory: EventCategory.FESTIVAL,
      userId: user[12].id,
    },
    {
      eventName: "Food Festival",
      startDate: new Date("2026-08-05T10:00:00"),
      endDate: new Date("2026-08-07T22:00:00"),
      imageUrl: "https://picsum.photos/seed/food/800/400",
      location: "Medan",
      description:
        "The ultimate culinary journey through the best of Medan street food.",
      seatTotal: 700,
      eventType: EventType.FREE,
      eventCategory: EventCategory.FESTIVAL,
      userId: user[13].id,
    },
    {
      eventName: "Tech Community Meetup",
      startDate: new Date("2026-08-10T18:00:00"),
      endDate: new Date("2026-08-10T21:00:00"),
      imageUrl: "https://picsum.photos/seed/tech/800/400",
      location: "Jakarta",
      description:
        "Networking session for developers, designers, and tech enthusiasts.",
      seatTotal: 150,
      eventType: EventType.FREE,
      eventCategory: EventCategory.OTHER,
      userId: user[14].id,
    },
    {
      eventName: "Creative Community Night",
      startDate: new Date("2026-08-12T19:00:00"),
      endDate: new Date("2026-08-12T22:00:00"),
      imageUrl: "https://picsum.photos/seed/creative/800/400",
      location: "Depok",
      description: "A cozy sharing session for local artists and creators.",
      seatTotal: 120,
      eventType: EventType.FREE,
      eventCategory: EventCategory.OTHER,
      userId: user[15].id,
    },
    {
      eventName: "Jazz Evening",
      startDate: new Date("2026-08-20T20:00:00"),
      endDate: new Date("2026-08-20T23:00:00"),
      imageUrl: "https://picsum.photos/seed/jazz/800/400",
      location: "Jakarta",
      description: "Smooth jazz music concert to end your weekday perfectly.",
      seatTotal: 400,
      eventType: EventType.PAID,
      eventCategory: EventCategory.CONCERT,
      userId: user[16].id,
    },
    {
      eventName: "Indie Music Fest",
      startDate: new Date("2026-08-25T17:00:00"),
      endDate: new Date("2026-08-25T23:59:00"),
      imageUrl: "https://picsum.photos/seed/indie/800/400",
      location: "Solo",
      description:
        "Outdoor music festival featuring rising stars of the indie scene.",
      seatTotal: 600,
      eventType: EventType.PAID,
      eventCategory: EventCategory.CONCERT,
      userId: user[17].id,
    },
    {
      eventName: "Finance Seminar",
      startDate: new Date("2026-09-01T09:00:00"),
      endDate: new Date("2026-09-01T15:00:00"),
      imageUrl: "https://picsum.photos/seed/finance/800/400",
      location: "Jakarta",
      description: "Financial planning and personal wealth management seminar.",
      seatTotal: 300,
      eventType: EventType.FREE,
      eventCategory: EventCategory.SEMINAR,
      userId: user[18].id,
    },
    {
      eventName: "Investment Workshop",
      startDate: new Date("2026-09-05T10:00:00"),
      endDate: new Date("2026-09-05T16:00:00"),
      imageUrl: "https://picsum.photos/seed/investment/800/400",
      location: "Surabaya",
      description: "Hands-on workshop about stock market and crypto analysis.",
      seatTotal: 180,
      eventType: EventType.PAID,
      eventCategory: EventCategory.WORKSHOP,
      userId: user[19].id,
    },
    {
      eventName: "City Cycling",
      startDate: new Date("2026-09-10T06:00:00"),
      endDate: new Date("2026-09-10T11:00:00"),
      imageUrl: "https://picsum.photos/seed/cycle/800/400",
      location: "Semarang",
      description:
        "Join hundreds of cyclists to explore the heritage of Semarang.",
      seatTotal: 500,
      eventType: EventType.FREE,
      eventCategory: EventCategory.SPORTS,
      userId: user[20].id,
    },
    {
      eventName: "Art & Culture Expo",
      startDate: new Date("2026-09-15T10:00:00"),
      endDate: new Date("2026-09-17T21:00:00"),
      imageUrl: "https://picsum.photos/seed/culture/800/400",
      location: "Yogyakarta",
      description:
        "Exhibition of traditional art combined with modern aesthetics.",
      seatTotal: 350,
      eventType: EventType.PAID,
      eventCategory: EventCategory.EXHIBITION,
      userId: user[21].id,
    },
    {
      eventName: "Traditional Festival",
      startDate: new Date("2026-09-20T08:00:00"),
      endDate: new Date("2026-09-21T22:00:00"),
      imageUrl: "https://picsum.photos/seed/tradition/800/400",
      location: "Padang",
      description:
        "Cultural festival showcasing the rich heritage of Minangkabau.",
      seatTotal: 800,
      eventType: EventType.FREE,
      eventCategory: EventCategory.FESTIVAL,
      userId: user[22].id,
    },
    {
      eventName: "Open Community Talk",
      startDate: new Date("2026-09-25T19:00:00"),
      endDate: new Date("2026-09-25T21:30:00"),
      imageUrl: "https://picsum.photos/seed/talk/800/400",
      location: "Bekasi",
      description: "Open floor for anyone to share stories and ideas.",
      seatTotal: 100,
      eventType: EventType.FREE,
      eventCategory: EventCategory.OTHER,
      userId: user[23].id,
    },
    {
      eventName: "Coffee Brewing Masterclass",
      startDate: new Date("2026-10-05T13:00:00"),
      endDate: new Date("2026-10-05T17:00:00"),
      imageUrl: "https://picsum.photos/seed/coffee/800/400",
      location: "Bandung",
      description:
        "Learn to brew coffee like a pro barista using various techniques.",
      seatTotal: 50,
      eventType: EventType.PAID,
      eventCategory: EventCategory.WORKSHOP,
      userId: user[24].id,
    },
    {
      eventName: "Annual Book Fair 2026",
      startDate: new Date("2026-10-12T09:00:00"),
      endDate: new Date("2026-10-19T21:00:00"),
      imageUrl: "https://picsum.photos/seed/book/800/400",
      location: "Jakarta",
      description:
        "Biggest book exhibition of the year with exclusive discounts.",
      seatTotal: 2000,
      eventType: EventType.FREE,
      eventCategory: EventCategory.EXHIBITION,
      userId: user[25].id,
    },
    {
      eventName: "Cyber Security Conference",
      startDate: new Date("2026-11-01T09:00:00"),
      endDate: new Date("2026-11-02T18:00:00"),
      imageUrl: "https://picsum.photos/seed/security/800/400",
      location: "Bali",
      description: "Deep dive into future security trends and ethical hacking.",
      seatTotal: 450,
      eventType: EventType.PAID,
      eventCategory: EventCategory.SEMINAR,
      userId: user[26].id,
    },
    {
      eventName: "Glow in the Dark Yoga",
      startDate: new Date("2026-11-15T18:30:00"),
      endDate: new Date("2026-11-15T20:30:00"),
      imageUrl: "https://picsum.photos/seed/yoga/800/400",
      location: "Jakarta",
      description:
        "Unique yoga experience with neon lights and electronic music.",
      seatTotal: 100,
      eventType: EventType.PAID,
      eventCategory: EventCategory.SPORTS,
      userId: user[27].id,
    },
    {
      eventName: "Indie Game Dev Meetup",
      startDate: new Date("2026-12-01T14:00:00"),
      endDate: new Date("2026-12-01T20:00:00"),
      imageUrl: "https://picsum.photos/seed/game/800/400",
      location: "Yogyakarta",
      description:
        "Showcase your indie games to the community and get feedback.",
      seatTotal: 150,
      eventType: EventType.FREE,
      eventCategory: EventCategory.OTHER,
      userId: user[28].id,
    },
    {
      eventName: "New Year Eve Fireworks Party",
      startDate: new Date("2026-12-31T20:00:00"),
      endDate: new Date("2027-01-01T02:00:00"),
      imageUrl: "https://picsum.photos/seed/party/800/400",
      location: "Ancol, Jakarta",
      description: "Celebrate the end of 2026 with an amazing fireworks party.",
      seatTotal: 5000,
      eventType: EventType.PAID,
      eventCategory: EventCategory.FESTIVAL,
      userId: user[29].id,
    },
  ];

  await prisma.event.createMany({
    data: events,
    skipDuplicates: true,
  });
}
