import { Role } from "../../../generated/prisma/enums";
import { prisma } from "../../../src/config/prisma-client.config";

const users = [
  {
    username: "lunar.events",
    email: "lunar.events@event.com",
    password: "hashedpassword",
    displayName: "Lunar Events",
    bio: "Event organizer focused on concerts and festivals.",
    avatarUrl: "https://picsum.photos/seed/lunar/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "skylineeo",
    email: "skylineeo@event.com",
    password: "hashedpassword",
    displayName: "Skyline EO",
    bio: "Managing premium urban and corporate events.",
    avatarUrl: "https://picsum.photos/seed/skyline/300/300",
    location: "Bandung",
    role: Role.organizer,
  },
  {
    username: "auroraevent",
    email: "auroraevent@event.com",
    password: "hashedpassword",
    displayName: "Aurora Event",
    bio: "Creative workshops and inspiring seminars.",
    avatarUrl: "https://picsum.photos/seed/aurora/300/300",
    location: "Surabaya",
    role: Role.organizer,
  },
  {
    username: "nexusevent",
    email: "nexusevent@event.com",
    password: "hashedpassword",
    displayName: "Nexus Event",
    bio: "Connecting people through meaningful events.",
    avatarUrl: "https://picsum.photos/seed/nexus/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "urbanstage",
    email: "urbanstage@event.com",
    password: "hashedpassword",
    displayName: "Urban Stage",
    bio: "Live performances and city-scale entertainment.",
    avatarUrl: "https://picsum.photos/seed/urbanstage/300/300",
    location: "Yogyakarta",
    role: Role.organizer,
  },
  {
    username: "brightagenda",
    email: "brightagenda@event.com",
    password: "hashedpassword",
    displayName: "Bright Agenda",
    bio: "Educational and motivational events organizer.",
    avatarUrl: "https://picsum.photos/seed/brightagenda/300/300",
    location: "Malang",
    role: Role.organizer,
  },
  {
    username: "eventoria",
    email: "eventoria@event.com",
    password: "hashedpassword",
    displayName: "Eventoria",
    bio: "Your gateway to curated experiences.",
    avatarUrl: "https://picsum.photos/seed/eventoria/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "horizonevents",
    email: "horizonevents@event.com",
    password: "hashedpassword",
    displayName: "Horizon Events",
    bio: "Large-scale conferences and exhibitions.",
    avatarUrl: "https://picsum.photos/seed/horizon/300/300",
    location: "Bali",
    role: Role.organizer,
  },
  {
    username: "momentum.id",
    email: "momentum.id@event.com",
    password: "hashedpassword",
    displayName: "Momentum ID",
    bio: "Momentum-driven events for modern audiences.",
    avatarUrl: "https://picsum.photos/seed/momentum/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "sparkvent",
    email: "sparkvent@event.com",
    password: "hashedpassword",
    displayName: "Sparkvent",
    bio: "Igniting ideas through impactful events.",
    avatarUrl: "https://picsum.photos/seed/sparkvent/300/300",
    location: "Semarang",
    role: Role.organizer,
  },

  {
    username: "infiniteeo",
    email: "infiniteeo@event.com",
    password: "hashedpassword",
    displayName: "Infinite EO",
    bio: "Endless possibilities in event experiences.",
    avatarUrl: "https://picsum.photos/seed/infinite/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "stagecraft",
    email: "stagecraft@event.com",
    password: "hashedpassword",
    displayName: "Stagecraft",
    bio: "Professional stage and event production.",
    avatarUrl: "https://picsum.photos/seed/stagecraft/300/300",
    location: "Bandung",
    role: Role.organizer,
  },
  {
    username: "eventhaus",
    email: "eventhaus@event.com",
    password: "hashedpassword",
    displayName: "Eventhaus",
    bio: "Modern event concepts and execution.",
    avatarUrl: "https://picsum.photos/seed/eventhaus/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "pulsevent",
    email: "pulsevent@event.com",
    password: "hashedpassword",
    displayName: "Pulsevent",
    bio: "Events that move with the pulse of trends.",
    avatarUrl: "https://picsum.photos/seed/pulsevent/300/300",
    location: "Surabaya",
    role: Role.organizer,
  },
  {
    username: "orion.events",
    email: "orion.events@event.com",
    password: "hashedpassword",
    displayName: "Orion Events",
    bio: "Guiding events with stellar precision.",
    avatarUrl: "https://picsum.photos/seed/orion/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "zenith.pro",
    email: "zenith.pro@event.com",
    password: "hashedpassword",
    displayName: "Zenith Production",
    bio: "High-end corporate gatherings and gala nights.",
    avatarUrl: "https://picsum.photos/seed/zenith/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "vivid.expo",
    email: "vivid.expo@event.com",
    password: "hashedpassword",
    displayName: "Vivid Expo",
    bio: "Bringing art and trade shows to life.",
    avatarUrl: "https://picsum.photos/seed/vivid/300/300",
    location: "Yogyakarta",
    role: Role.organizer,
  },
  {
    username: "stellar.organizer",
    email: "stellar@event.com",
    password: "hashedpassword",
    displayName: "Stellar Organizer",
    bio: "Reach for the stars with our premium services.",
    avatarUrl: "https://picsum.photos/seed/stellar/300/300",
    location: "Medan",
    role: Role.organizer,
  },
  {
    username: "beyond.limits",
    email: "beyond@event.com",
    password: "hashedpassword",
    displayName: "Beyond Limits",
    bio: "Pushing boundaries in outdoor adventure events.",
    avatarUrl: "https://picsum.photos/seed/beyond/300/300",
    location: "Bali",
    role: Role.organizer,
  },
  {
    username: "core.project",
    email: "core.project@event.com",
    password: "hashedpassword",
    displayName: "Core Project",
    bio: "The heart of every successful activation.",
    avatarUrl: "https://picsum.photos/seed/core/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "prime.agenda",
    email: "prime@event.com",
    password: "hashedpassword",
    displayName: "Prime Agenda",
    bio: "Tailored luxury weddings and private parties.",
    avatarUrl: "https://picsum.photos/seed/prime/300/300",
    location: "Semarang",
    role: Role.organizer,
  },
  {
    username: "nova.creative",
    email: "nova@event.com",
    password: "hashedpassword",
    displayName: "Nova Creative",
    bio: "Innovative solutions for digital-first events.",
    avatarUrl: "https://picsum.photos/seed/nova/300/300",
    location: "Bandung",
    role: Role.organizer,
  },
  {
    username: "epic.vibes",
    email: "epic.vibes@event.com",
    password: "hashedpassword",
    displayName: "Epic Vibes",
    bio: "We curate the best nightlife and music tours.",
    avatarUrl: "https://picsum.photos/seed/epic/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "nexus.point",
    email: "nexus.point@event.com",
    password: "hashedpassword",
    displayName: "Nexus Point",
    bio: "Your meeting point for tech and innovation.",
    avatarUrl: "https://picsum.photos/seed/nexuspoint/300/300",
    location: "Tangerang",
    role: Role.organizer,
  },
  {
    username: "echo.fest",
    email: "echo@event.com",
    password: "hashedpassword",
    displayName: "Echo Fest",
    bio: "Sound, light, and unforgettable memories.",
    avatarUrl: "https://picsum.photos/seed/echo/300/300",
    location: "Surabaya",
    role: Role.organizer,
  },
  {
    username: "canvas.event",
    email: "canvas@event.com",
    password: "hashedpassword",
    displayName: "Canvas Event",
    bio: "Painting the town with colorful community events.",
    avatarUrl: "https://picsum.photos/seed/canvas/300/300",
    location: "Makassar",
    role: Role.organizer,
  },
  {
    username: "titan.organizer",
    email: "titan@event.com",
    password: "hashedpassword",
    displayName: "Titan Organizer",
    bio: "Handling massive crowds with professional care.",
    avatarUrl: "https://picsum.photos/seed/titan/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
  {
    username: "lumiere.eo",
    email: "lumiere@event.com",
    password: "hashedpassword",
    displayName: "Lumiere EO",
    bio: "Shining light on boutique social gatherings.",
    avatarUrl: "https://picsum.photos/seed/lumiere/300/300",
    location: "Solo",
    role: Role.organizer,
  },
  {
    username: "vantage.pro",
    email: "vantage@event.com",
    password: "hashedpassword",
    displayName: "Vantage Production",
    bio: "Strategic planning for corporate summits.",
    avatarUrl: "https://picsum.photos/seed/vantage/300/300",
    location: "Balikpapan",
    role: Role.organizer,
  },
  {
    username: "apex.events",
    email: "apex@event.com",
    password: "hashedpassword",
    displayName: "Apex Events",
    bio: "The peak of event management excellence.",
    avatarUrl: "https://picsum.photos/seed/apex/300/300",
    location: "Jakarta",
    role: Role.organizer,
  },
];

export async function seedUsers() {
  console.log("🌱 Seeding Users...");
  await prisma.user.createMany({
    data: users,
    skipDuplicates: true,
  });
}
